name: "Page Bank"
app_id: "app-pagebank"
customer_id: "yeti"
version: "1.0"
schemas:
  path: schemas/schema.graphql

resources:
  path: resources/*.rs
  route: /api

static:
  path: web
  route: /
  spa: true
  build:
    source: source
    command: npm run build

env:
  PAGEBANK_ORIGIN_URL: "https://www.example.com"
